# ===========================================
# GITREPOSITORY : Source du code pour FluxCD
# FluxCD surveille ce repo et synchronise les changements
# ===========================================
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: wave-app
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/jabdoulie/projet-m1
  ref:
    branch: main
  # Pour un repo privé, décommenter et configurer le secret
  # secretRef:
  #   name: github-credentials
